# Dependencies
markdown: kramdown
kramdown:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            MTC Analytical Services Project Pages
tagline:          'Bay Area Metro'
url:              http://bayareametro.github.io
shorturl:         bayareametro.github.io

author:
  name:           'Dev'
  url:            https://github.com/Devdev606

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/BayAreaMetro/BayAreaMetro.github.io/tree/master
  

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
